name: CICD

on:
  push:
    branches: [ main, develop, release ]
  pull_request:
    branches: [ main, develop, release ]
    
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses:actions/checkout@master
      
    - name: Run Super_Linter
      uses: github/super-linter@master
      env:
       DEFAULT_BRANCH: master
       GITHUB_TOKEN: ${{ secrets.GITHUB_TKEN }}
       
