name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
            
      - name: Install AStyle
        run: |
          sudo apt-get update -y
          sudo apt-get install -y astyle
          
      - name: Format Code with AStyle
        run: |
          astyle --options=astylerc.txt "build/*.c"

      - name: Check for Changes after Formatting
        run: |
          git diff --exit-code || { echo "Code formatting changes detected. Please commit the changes."; exit 1; }

      - name: Set up Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
        shell: bash

      - name: Debug Git Describe
        run: |
          TAG=$(git describe --abbrev=0 --tags --match "v*" 2>/dev/null || echo "No tags found")
          echo "Latest Tag: $TAG"
        shell: bash

      - name: Debug Branch Permission
        run: |
          git remote -v
          git branch -a
        shell: bash

      - name: Debug GitHub Token
        run: |
          echo "GitHub Token: $API_TOKEN_GITHUB"
        shell: bash

      - name: Extract Version Number
        id: extract_version
        run: |
          # Check commit message for vX.Y.Z pattern
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $COMMIT_MESSAGE =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            # Extract version number from commit message
            echo $COMMIT_MESSAGE | grep -oP 'v\d+\.\d+\.\d+' | sed 's/v//' > version.txt
          else
            # Try to get the latest tag, fallback to v1.0.0 if no tags found
            PREVIOUS_TAG=$(git describe --abbrev=0 --tags --match "v*" 2>/dev/null || echo "v1.0.0")
            # Extract the version number from the previous tag
            PREVIOUS_VERSION=$(echo $PREVIOUS_TAG | sed 's/v//')
            NEW_VERSION=$(echo $PREVIOUS_VERSION | awk -F. -v OFS=. '{++$3; print $1,$2,$3}')
            echo "v$NEW_VERSION" > version.txt
          fi
          
          cat version.txt
        shell: bash
  
      - name: Bump version and create tag
        if: github.event_name == 'push'
        run: |
          git add version.txt  # Add version.txt to the staging area
          NEW_VERSION=$(cat version.txt)  # Get version from version.txt
          # Commit the version number increment
          git commit -m "[version-bump] Bump version to $NEW_VERSION"
          # Create a new tag with the updated version number
          git tag $NEW_VERSION
          # Push changes and the new tag to the repository 
          git push origin main --tags
        shell: bash
