# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "develop", "release" ]
  pull_request:
    branches: [ "master", "develop", "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Development:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/checkout@v2
      - uses: per1234/artistic-style-action@v1
        with:
          name-patterns: |
            - '*.c'
            - '*.h'
            
     
